brave-intl/bat-ratios

package-lock.json
package.json
versions/currency.js

fixes: https://nodesecurity.io/advisories/737

Removed vulnerability

---

package-lock.json
package.json
test/utils.test.js
test/v1/index.test.js
versions/v1/workers.js

uses updated currency package and makes sure data is exposed
fixes #28

updated currency package with binance to uphold swap

---

server.js
test/v1/index.test.js

added test for uptime pingdom

---

.travis.yml
package-lock.json
package.json
server.js
versions/regexp.js

* updated deps
* grant permissive regexp to not fail on new uphold keys

updated deps and granted permissive regexp

---

server.js
test/v1/index.test.js
versions/index.js

not having it behind the v1 endpoint, caused robots to get 401s
fixes #50

moved middleware behind v1 endpoint

---

server.js
test/v1/index.test.js

added vary header and test

---

docker-compose.yml
fetch-and-insert.js
package-lock.json
package.json
test/utils.test.js

* updated deps
* fixed logging
* pulled volume in config

updated deps

---

README.md
server.js
test/v1/index.test.js

* added health check 200 so as to not report to sentry
* fixed tests
* updated development instructions

fixed tests and added notes

---

.github/workflows/ci.yml
capture-exception.js

- removed reference to staging
- removed 404 from sentry

Prod Release 2021-02-19_0

---

.github/workflows/ci.yml
base.yml
docker-compose.yml
package.json
server.js
test/v1/index.test.js
versions/cache.js
versions/documentation.js
versions/index.js
versions/middleware/prometheus.js
versions/schemas.js
versions/v2/coingecko.js
versions/v2/functions.js
versions/v2/index.js
versions/v2/swagger.js
yarn.lock

- add coingecko history
- update deps
- update metrics to ignore default values

Add coingecko history

---

.env.example
.github/workflows/ci.yml
README.md
docker-compose.yml
test/v1/index.test.js
versions/middleware/prometheus.js
versions/v2/coingecko.js

* changed ports for ratios dbs and added usd_24h_change for relative url
* found that alt currencies must be used with usd or other base currencies
* removed log

added 24hr change for currencies (#85)

---

test/v1/index.test.js
versions/v2/coingecko.js

* changed ports for ratios dbs and added usd_24h_change for relative url
* found that alt currencies must be used with usd or other base currencies
* removed log
* updated coingecko call to include multiple vs assets
* added reductions for multiple input assets

Add multi assets (#87)

---

test/v1/index.test.js
versions/v2/coingecko.js
versions/v2/index.js

* added arbitrary time comparison to spot
* added tests for spot pricing and timeframe
* used more relevant currencies for test
* removed 24 hr change
Co-authored-by: Halley Comet <halley@ninerealms.co>

added arbitrary time comparison to spot (#90)

---

versions/v2/coingecko.js

Co-authored-by: Halley Comet <halley@ninerealms.co>

clarified intent (#92)

---

test/v1/index.test.js
versions/v2/coingecko.js

- Support passing of comma separated currencies
- Include test and update other coin gecko test
https://github.com/brave-intl/bat-ratios/issues/121

Multi currency support

---

test/v1/index.test.js
versions/v2/coingecko.js

- Refactored some code because it was hard to make sense of what was happening
- Included test to verify contract address lookup functionality
- Also supports mixing contract addresses with ticker symbol in same request

Coingecko token contract address lookup

---

README.md
test/v1/index.test.js
versions/cache.js
versions/v2/coingecko.js

- Included a limit to the number of currencies and tokens allowed to be
sent in single request
- Added in a known currencies list for coingecko, we will filter based
upon this list. Should save some requests. List pulled from here:
https://api.coingecko.com/api/v3/simple/supported_vs_currencies
- Ran linter

Currency limits and validation

---

server.js

See https://github.com/brave-intl/bat-ratios/security/code-scanning/4

server.js: serve robots.txt from RAM

---

package.json
yarn.lock

Pin currency@1.6.8

---

versions/v2/functions.js

If the query params include query.module='token' && query.action='tokeninfo', then set a Cache-Control header of 14 days.

Add Cache-Control header to etherscan tokeninfo passthrough requests
